require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'fosscord' do
	config = use_native_modules!

	use_react_native!(:path => config["reactNativePath"])

	target 'fosscordTests' do
		inherit! :complete
		# Pods for testing
	end

	# Enables Flipper.
	#
	# Note that if you have use_frameworks! enabled, Flipper will not work and
	# you should disable these next few lines.
	use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})
	post_install do |installer|
		flipper_post_install(installer)
	installer.pods_project.targets.each do |target|
				# Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
				if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
						target.build_configurations.each do |config|
								config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
						end
				end
		end
	end
end

target 'fosscord-tvOS' do
	# Pods for fosscord-tvOS

	target 'fosscord-tvOSTests' do
		inherit! :search_paths
		# Pods for testing
	end
end
