import Color from 'color';
import {Platform} from 'react-native';
import {configureFonts} from 'react-native-paper';
import {ColorPalette, CustomTheme, Font} from '../../types';
import {CommonBaseColors} from './CommonColors';

const BaseColors = {
  background: Color('#263238'),
  foreground: Color('#B0BEC5'),
  text: Color('#607D8B'),
  selectionBackground: Color('#546E7A'),
  selectionForeground: Color('#FFFFFF'),
  buttons: Color('#2E3C43'),
  secondBackground: Color('#32424A'),
  disabled: Color('#415967'),
  contrast: Color('#1E272C'),
  active: Color('#314549'),
  border: Color('#2A373E'),
  highlight: Color('#425B67'),
  tree: Color('#546E7A70'),
  notifications: Color('#1E272C'),
  accent: Color('#009688'),
  excludedFilesColor: Color('#2E3C43'),
  green: Color('#c3e88d'),
  yellow: Color('#ffcb6b'),
  blue: Color('#82aaff'),
  red: Color('#f07178'),
  purple: Color('#c792ea'),
  orange: Color('#f78c6c'),
  cyan: Color('#89ddff'),
  gray: Color('#546e7a'),
  whiteBlack: Color('#eeffff'),
  error: Color('#ff5370'),
  link: Color('#80cbc4'),
};

const palette: ColorPalette = {
  primary100: CommonBaseColors.primary.lighten(1).hex(),
  primary95: CommonBaseColors.primary.lighten(0.9).hex(),
  primary90: CommonBaseColors.primary.lighten(0.8).hex(),
  primary85: CommonBaseColors.primary.lighten(0.7).hex(),
  primary80: CommonBaseColors.primary.lighten(0.6).hex(),
  primary75: CommonBaseColors.primary.lighten(0.5).hex(),
  primary70: CommonBaseColors.primary.lighten(0.4).hex(),
  primary65: CommonBaseColors.primary.lighten(0.3).hex(),
  primary60: CommonBaseColors.primary.lighten(0.2).hex(),
  primary55: CommonBaseColors.primary.lighten(0.1).hex(),
  primary50: CommonBaseColors.primary.hex(),
  primary45: CommonBaseColors.primary.darken(0.1).hex(),
  primary40: CommonBaseColors.primary.darken(0.2).hex(),
  primary35: CommonBaseColors.primary.darken(0.3).hex(),
  primary30: CommonBaseColors.primary.darken(0.4).hex(),
  primary25: CommonBaseColors.primary.darken(0.5).hex(),
  primary20: CommonBaseColors.primary.darken(0.6).hex(),
  primary15: CommonBaseColors.primary.darken(0.7).hex(),
  primary10: CommonBaseColors.primary.darken(0.8).hex(),
  primary5: CommonBaseColors.primary.darken(0.9).hex(),
  primary0: CommonBaseColors.primary.darken(1).hex(),
  secondary100: CommonBaseColors.secondary.lighten(1).hex(),
  secondary95: CommonBaseColors.secondary.lighten(0.9).hex(),
  secondary90: CommonBaseColors.secondary.lighten(0.8).hex(),
  secondary85: CommonBaseColors.primary.lighten(0.7).hex(),
  secondary80: CommonBaseColors.secondary.lighten(0.6).hex(),
  secondary75: CommonBaseColors.secondary.lighten(0.4).hex(),
  secondary70: CommonBaseColors.secondary.lighten(0.4).hex(),
  secondary65: CommonBaseColors.secondary.lighten(0.3).hex(),
  secondary60: CommonBaseColors.secondary.lighten(0.2).hex(),
  secondary55: CommonBaseColors.secondary.lighten(0.1).hex(),
  secondary50: CommonBaseColors.secondary.hex(),
  secondary45: CommonBaseColors.secondary.lighten(0.1).hex(),
  secondary40: CommonBaseColors.secondary.lighten(0.2).hex(),
  secondary35: CommonBaseColors.secondary.lighten(0.3).hex(),
  secondary30: CommonBaseColors.secondary.darken(0.4).hex(),
  secondary25: CommonBaseColors.secondary.darken(0.5).hex(),
  secondary20: CommonBaseColors.secondary.darken(0.6).hex(),
  secondary15: CommonBaseColors.secondary.darken(0.7).hex(),
  secondary10: CommonBaseColors.secondary.darken(0.8).hex(),
  secondary5: CommonBaseColors.secondary.darken(0.9).hex(),
  secondary0: CommonBaseColors.secondary.darken(1).hex(),
  error100: BaseColors.error.lighten(1).hex(),
  error95: BaseColors.error.lighten(0.9).hex(),
  error90: BaseColors.error.lighten(0.8).hex(),
  error85: BaseColors.error.lighten(0.7).hex(),
  error80: BaseColors.error.lighten(0.6).hex(),
  error75: BaseColors.error.lighten(0.5).hex(),
  error70: BaseColors.error.lighten(0.4).hex(),
  error65: BaseColors.error.lighten(0.3).hex(),
  error60: BaseColors.error.lighten(0.2).hex(),
  error55: BaseColors.error.lighten(0.1).hex(),
  error50: BaseColors.error.hex(),
  error45: BaseColors.error.darken(0.1).hex(),
  error40: BaseColors.error.darken(0.2).hex(),
  error35: BaseColors.error.darken(0.3).hex(),
  error30: BaseColors.error.darken(0.4).hex(),
  error25: BaseColors.error.darken(0.5).hex(),
  error20: BaseColors.error.darken(0.6).hex(),
  error15: BaseColors.error.darken(0.7).hex(),
  error10: BaseColors.error.darken(0.8).hex(),
  error5: BaseColors.error.darken(0.9).hex(),
  error0: BaseColors.error.darken(1).hex(),
  green100: BaseColors.green.lighten(1).hex(),
  green95: BaseColors.green.lighten(0.9).hex(),
  green90: BaseColors.green.lighten(0.8).hex(),
  green85: BaseColors.green.lighten(0.7).hex(),
  green80: BaseColors.green.lighten(0.6).hex(),
  green75: BaseColors.green.lighten(0.5).hex(),
  green70: BaseColors.green.lighten(0.4).hex(),
  green65: BaseColors.green.lighten(0.3).hex(),
  green60: BaseColors.green.lighten(0.2).hex(),
  green55: BaseColors.green.lighten(0.1).hex(),
  green50: BaseColors.green.hex(),
  green45: BaseColors.green.darken(0.1).hex(),
  green40: BaseColors.green.darken(0.2).hex(),
  green35: BaseColors.green.darken(0.3).hex(),
  green30: BaseColors.green.darken(0.3).hex(),
  green25: BaseColors.green.darken(0.4).hex(),
  green20: BaseColors.green.darken(0.6).hex(),
  green15: BaseColors.green.darken(0.7).hex(),
  green10: BaseColors.green.darken(0.8).hex(),
  green5: BaseColors.green.darken(0.8).hex(),
  green0: BaseColors.green.darken(1).hex(),
  gray100: BaseColors.gray.lighten(1).hex(),
  gray95: BaseColors.gray.lighten(0.9).hex(),
  gray90: BaseColors.gray.lighten(0.8).hex(),
  gray85: BaseColors.gray.lighten(0.7).hex(),
  gray80: BaseColors.gray.lighten(0.6).hex(),
  gray75: BaseColors.gray.lighten(0.5).hex(),
  gray70: BaseColors.gray.lighten(0.4).hex(),
  gray65: BaseColors.gray.lighten(0.3).hex(),
  gray60: BaseColors.gray.lighten(0.2).hex(),
  gray55: BaseColors.gray.lighten(0.1).hex(),
  gray50: BaseColors.gray.hex(),
  gray45: BaseColors.gray.darken(0.1).hex(),
  gray40: BaseColors.gray.darken(0.2).hex(),
  gray35: BaseColors.gray.darken(0.3).hex(),
  gray30: BaseColors.gray.darken(0.4).hex(),
  gray25: BaseColors.gray.darken(0.5).hex(),
  gray20: BaseColors.gray.darken(0.6).hex(),
  gray15: BaseColors.gray.darken(0.7).hex(),
  gray10: BaseColors.gray.darken(0.8).hex(),
  gray5: BaseColors.gray.darken(0.9).hex(),
  gray0: BaseColors.gray.darken(1).hex(),
  red100: BaseColors.red.lighten(1).hex(),
  red95: BaseColors.red.lighten(0.9).hex(),
  red90: BaseColors.red.lighten(0.8).hex(),
  red85: BaseColors.red.lighten(0.7).hex(),
  red80: BaseColors.red.lighten(0.6).hex(),
  red75: BaseColors.red.lighten(0.5).hex(),
  red70: BaseColors.red.lighten(0.4).hex(),
  red65: BaseColors.red.lighten(0.3).hex(),
  red60: BaseColors.red.lighten(0.2).hex(),
  red55: BaseColors.red.lighten(0.1).hex(),
  red50: BaseColors.red.hex(),
  red45: BaseColors.red.darken(0.1).hex(),
  red40: BaseColors.red.darken(0.2).hex(),
  red35: BaseColors.red.darken(0.3).hex(),
  red30: BaseColors.red.darken(0.4).hex(),
  red25: BaseColors.red.darken(0.5).hex(),
  red20: BaseColors.red.darken(0.6).hex(),
  red15: BaseColors.red.darken(0.7).hex(),
  red10: BaseColors.red.darken(0.8).hex(),
  red5: BaseColors.red.darken(0.9).hex(),
  red0: BaseColors.red.darken(1).hex(),
  yellow100: BaseColors.yellow.lighten(1).hex(),
  yellow95: BaseColors.yellow.lighten(0.9).hex(),
  yellow90: BaseColors.yellow.lighten(0.8).hex(),
  yellow85: BaseColors.yellow.lighten(0.7).hex(),
  yellow80: BaseColors.yellow.lighten(0.6).hex(),
  yellow75: BaseColors.yellow.lighten(0.5).hex(),
  yellow70: BaseColors.yellow.lighten(0.4).hex(),
  yellow65: BaseColors.yellow.lighten(0.3).hex(),
  yellow60: BaseColors.yellow.lighten(0.2).hex(),
  yellow55: BaseColors.yellow.lighten(0.1).hex(),
  yellow50: BaseColors.yellow.hex(),
  yellow45: BaseColors.yellow.darken(0.1).hex(),
  yellow40: BaseColors.yellow.darken(0.2).hex(),
  yellow35: BaseColors.yellow.darken(0.3).hex(),
  yellow30: BaseColors.yellow.darken(0.4).hex(),
  yellow25: BaseColors.yellow.darken(0.5).hex(),
  yellow20: BaseColors.yellow.darken(0.6).hex(),
  yellow15: BaseColors.yellow.darken(0.7).hex(),
  yellow10: BaseColors.yellow.darken(0.8).hex(),
  yellow5: BaseColors.yellow.darken(0.9).hex(),
  yellow0: BaseColors.yellow.darken(1).hex(),
  purple100: BaseColors.purple.lighten(1).hex(),
  purple95: BaseColors.purple.lighten(0.9).hex(),
  purple90: BaseColors.purple.lighten(0.8).hex(),
  purple85: BaseColors.purple.lighten(0.7).hex(),
  purple80: BaseColors.purple.lighten(0.6).hex(),
  purple75: BaseColors.purple.lighten(0.5).hex(),
  purple70: BaseColors.purple.lighten(0.4).hex(),
  purple65: BaseColors.purple.lighten(0.3).hex(),
  purple60: BaseColors.purple.lighten(0.2).hex(),
  purple55: BaseColors.purple.lighten(0.1).hex(),
  purple50: BaseColors.purple.hex(),
  purple45: BaseColors.purple.darken(0.1).hex(),
  purple40: BaseColors.purple.darken(0.2).hex(),
  purple35: BaseColors.purple.darken(0.3).hex(),
  purple30: BaseColors.purple.darken(0.4).hex(),
  purple25: BaseColors.purple.darken(0.5).hex(),
  purple20: BaseColors.purple.darken(0.6).hex(),
  purple15: BaseColors.purple.darken(0.7).hex(),
  purple10: BaseColors.purple.darken(0.8).hex(),
  purple5: BaseColors.purple.darken(0.9).hex(),
  purple0: BaseColors.purple.darken(1).hex(),
  tertiary100: 'rgba(255, 255, 255, 1)',
  tertiary99: 'rgba(255, 251, 250, 1)',
  tertiary95: 'rgba(255, 236, 241, 1)',
  tertiary90: 'rgba(255, 216, 228, 1)',
  tertiary80: 'rgba(239, 184, 200, 1)',
  tertiary70: 'rgba(210, 157, 172, 1)',
  tertiary60: 'rgba(181, 131, 146, 1)',
  tertiary50: 'rgba(152, 105, 119, 1)',
  tertiary40: 'rgba(125, 82, 96, 1)',
  tertiary30: 'rgba(99, 59, 72, 1)',
  tertiary20: 'rgba(73, 37, 50, 1)',
  tertiary10: 'rgba(49, 17, 29, 1)',
  tertiary0: 'rgba(0, 0, 0, 1)',
  background100: BaseColors.background.lighten(1).hex(),
  background95: BaseColors.background.lighten(0.9).hex(),
  background90: BaseColors.background.lighten(0.8).hex(),
  background85: BaseColors.background.lighten(0.7).hex(),
  background80: BaseColors.background.lighten(0.6).hex(),
  background75: BaseColors.background.lighten(0.5).hex(),
  background70: BaseColors.background.lighten(0.4).hex(),
  background65: BaseColors.background.lighten(0.3).hex(),
  background60: BaseColors.background.lighten(0.2).hex(),
  background55: BaseColors.background.lighten(0.1).hex(),
  background50: BaseColors.background.hex(),
  background45: BaseColors.background.darken(0.1).hex(),
  background40: BaseColors.background.darken(0.2).hex(),
  background35: BaseColors.background.darken(0.3).hex(),
  background30: BaseColors.background.darken(0.4).hex(),
  background25: BaseColors.background.darken(0.5).hex(),
  background20: BaseColors.background.darken(0.6).hex(),
  background15: BaseColors.background.darken(0.7).hex(),
  background10: BaseColors.background.darken(0.8).hex(),
  background5: BaseColors.background.darken(0.9).hex(),
  background0: BaseColors.background.darken(1).hex(),
  backgroundSecondary100: BaseColors.secondBackground.lighten(1).hex(),
  backgroundSecondary95: BaseColors.secondBackground.lighten(0.9).hex(),
  backgroundSecondary90: BaseColors.secondBackground.lighten(0.8).hex(),
  backgroundSecondary85: BaseColors.secondBackground.lighten(0.7).hex(),
  backgroundSecondary80: BaseColors.secondBackground.lighten(0.6).hex(),
  backgroundSecondary75: BaseColors.secondBackground.lighten(0.5).hex(),
  backgroundSecondary70: BaseColors.secondBackground.lighten(0.4).hex(),
  backgroundSecondary65: BaseColors.secondBackground.lighten(0.3).hex(),
  backgroundSecondary60: BaseColors.secondBackground.lighten(0.2).hex(),
  backgroundSecondary55: BaseColors.secondBackground.lighten(0.1).hex(),
  backgroundSecondary50: BaseColors.secondBackground.hex(),
  backgroundSecondary45: BaseColors.secondBackground.darken(0.1).hex(),
  backgroundSecondary40: BaseColors.secondBackground.darken(0.2).hex(),
  backgroundSecondary35: BaseColors.secondBackground.darken(0.3).hex(),
  backgroundSecondary30: BaseColors.secondBackground.darken(0.4).hex(),
  backgroundSecondary25: BaseColors.secondBackground.darken(0.5).hex(),
  backgroundSecondary20: BaseColors.secondBackground.darken(0.6).hex(),
  backgroundSecondary15: BaseColors.secondBackground.darken(0.7).hex(),
  backgroundSecondary10: BaseColors.secondBackground.darken(0.8).hex(),
  backgroundSecondary5: BaseColors.secondBackground.darken(0.9).hex(),
  backgroundSecondary0: BaseColors.secondBackground.darken(1).hex(),
};

const typeface = {
  brandRegular: Platform.select({
    web: 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif',
    ios: 'System',
    default: 'sans-serif',
  }),
  weightRegular: '400' as Font['fontWeight'],

  plainMedium: Platform.select({
    web: 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif',
    ios: 'System',
    default: 'sans-serif-medium',
  }),
  weightMedium: '500' as Font['fontWeight'],
};

const opacity = {
  level1: 0.08,
  level2: 0.12,
  level3: 0.16,
  level4: 0.38,
};

const Theme: CustomTheme = {
  name: 'Default Dark',
  dark: true,
  roundness: 4,
  mode: 'adaptive',
  version: 3,
  isV3: true,
  colors: {
    palette,
    text: BaseColors.text.hex(),
    textMuted: BaseColors.text.darken(0.3).hex(),
    selectionBackground: BaseColors.selectionBackground.hex(),
    selectionForeground: BaseColors.selectionForeground.hex(),
    buttons: BaseColors.buttons.hex(),
    disabled: BaseColors.disabled.hex(),
    contrast: BaseColors.contrast.hex(),
    active: BaseColors.active.hex(),
    border: BaseColors.border.hex(),
    highlight: BaseColors.highlight.hex(),
    tree: BaseColors.tree.hex(),
    notifications: BaseColors.notifications.hex(),
    accent: BaseColors.accent.hex(),
    whiteBlack: BaseColors.whiteBlack.hex(),
    link: BaseColors.cyan.hex(),
    primary: palette.primary50,
    primaryContainer: palette.primary30,
    secondary: palette.secondary50,
    secondaryContainer: palette.secondary30,
    tertiary: palette.tertiary50,
    tertiaryContainer: palette.tertiary30,
    surface: palette.background50,
    surfaceVariant: palette.backgroundSecondary60,
    surfaceDisabled: Color(palette.background90)
      .alpha(opacity.level2)
      .rgb()
      .string(),
    background: palette.background50,
    error: palette.error50,
    errorContainer: palette.error30,
    onPrimary: BaseColors.whiteBlack.hex(),
    onPrimaryContainer: BaseColors.orange.hex(),
    onSecondary: BaseColors.purple.hex(),
    onSecondaryContainer: BaseColors.yellow.hex(),
    onTertiary: BaseColors.red.hex(),
    onTertiaryContainer: BaseColors.red.hex(),
    onSurface: BaseColors.whiteBlack.hex(),
    onSurfaceVariant: BaseColors.whiteBlack.hex(),
    onSurfaceDisabled: BaseColors.green.alpha(opacity.level4).rgb().string(),
    onError: BaseColors.red.hex(),
    onErrorContainer: BaseColors.red.hex(),
    onBackground: BaseColors.purple.hex(),
    outline: BaseColors.border.hex(),
    outlineVariant: palette.backgroundSecondary30,
    inverseSurface: palette.background90,
    inverseOnSurface: palette.background20,
    inversePrimary: palette.primary40,
    shadow: palette.background0,
    scrim: palette.background0,
    backdrop: Color(palette.backgroundSecondary20).alpha(0.4).rgb().string(),
    elevation: {
      level0: 'transparent',
      // Note: Color values with transparency cause RN to transfer shadows to children nodes
      // instead of View component in Surface. Providing solid background fixes the issue.
      // Opaque color values generated with `palette.primary80` used as background
      level1: 'rgb(37, 35, 42)', // palette.primary80, alpha 0.05
      level2: 'rgb(44, 40, 49)', // palette.primary80, alpha 0.08
      level3: 'rgb(49, 44, 56)', // palette.primary80, alpha 0.11
      level4: 'rgb(51, 46, 58)', // palette.primary80, alpha 0.12
      level5: 'rgb(52, 49, 63)', // palette.primary80, alpha 0.14
    },
  },
  fonts: configureFonts({
    config: {
      fontFamily: 'source-sans-regular',
    },
  }),
  animation: {
    scale: 1.0,
  },
};

export default Theme;
